### ISSUE TITLE
Better handle spawn failures

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/spring-launcher#46]
From user log:

```
[2024-02-18 10:17:47.744] [error] Unexpected error occurred.
[2024-02-18 10:17:47.745] [error] {
  createIssue: '[function] function () { [native code] }',
  error: 'Error: spawn UNKNOWN\n' +
    '    at ChildProcess.spawn (node:internal/child_process:414:11)\n' +
    '    at spawn (node:child_process:784:9)\n' +
    '    at Launcher.launchSpring (C:\\Users\\user\\AppData\\Local\\Programs\\Beyond-All-Reason\\resources\\app.asar\\src\\engine_launcher.js:170:18)\n' +
    '    at Launcher.launch (C:\\Users\\user\\AppData\\Local\\Programs\\Beyond-All-Reason\\resources\\app.asar\\src\\engine_launcher.js:137:9)\n' +
```

**Comment by p2004a** [comment]
We now have https://github.com/beyond-all-reason/spring-launcher/commit/729c4c1240da42d5f02a031eea12d9cb7b5f276a so meh
